spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spoty?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
