spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spoty?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  redis:
    host: 127.0.0.1
    port: 6379
  jwt:
    secretKey: JJWCJHLCGCBG13245
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: changeun28@gmail.com
    password: kmewmzbvwqwzzfcp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

