spring:
  datasource:
#    url: jdbc:mysql://sent.cjiuhacfunbj.ap-northeast-2.rds.amazonaws.com:3306/SENT?useUnicode=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: Sent123!
    url: jdbc:mysql://localhost:3306/spoty?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jwt:
    secretKey: JJWCJHLCGCBG13245
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        ddl-auto: update
#        use-new-id-generator-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: changeun28@gmail.com
    password: kmewmzbvwqwzzfcp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 337685329967-8sb87jn3dre6qoj6vonp2p6peql3lp9u.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

