spring:
  datasource:
    url: jdbc:mysql://sent.cjiuhacfunbj.ap-northeast-2.rds.amazonaws.com:3306/SENT?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin 
    password: Sent123!
  jwt:
    secretKey: JJWCJHLCGCBG13245
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none
        use-new-id-generator-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: changeun28@gmail.com
    password: kmewmzbvwqwzzfcp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



