spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spoty?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
  jwt:
    secretKey: JJWCJHLCGCBG13245
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: changeun28@gmail.com
    password: kmewmzbvwqwzzfcp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 337685329967-8sb87jn3dre6qoj6vonp2p6peql3lp9u.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          naver:
            client-id: GBgsJl5wruCH8uAzbzzh
            client-secret: 9IPYBUloa9
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - email
          kakao:
            client-id: 338d1c039bfac4568e74a7e029af8af2
            client-secret: Z9skMea5xxeYKrSjiCWNZ76AVPG2XrVW
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버에서 넘어오는 회원정보를 json으로 받는데, response 라는 키값으로 네이버가 리턴해줌.
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
